services:
  - type: web
    name: codeshui-backend
    env: node
    plan: free
    rootDir: ./
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
    healthCheckPath: /health
